### PR TITLE
Update programs_list.yml

### PR DESCRIPTION
**Pull request by yuhengcai1**
Update a lot of program ranking
First move Duke and NWU from A+ to A, They are not a traditional top CS school and both of them are extremely expensive.  Move hkust mphil to A, this program is fully funded, but with bad job seeking and need another PHD application. Unlike UBC, It doesn't have the privileges of Canada. Update about wisc PMP program ranking.
Move Harvard and Upenn DS programs, actually I find it very hard, I can not agree that these programs are better than UIUC MSCS. They are also no better than Stanford's EE program. And I hope there will be another S+ ranking for these programs. Update GT CSE from A to A+
Update UVA MSCS to B+, UVA is google target school.

### CODE REVIEW

**Comment by xichenpan** [comment]
Hi @yuhengcai1, thanks a lot for your commit and many valuable insights, the point is our ranking is based on the entry bar for undergraduate student at Mainland China, so there maybe many programs which are easy to get in like GT CSE but very promising in pursuing a PhD degree, and many programs which are difficult to get enrolled but poor in placement.

Since the placement is very random and has close relation with the admission preference (like minority), also, rank BEST programs will lead to many conflict of interests. OpenCSApp aims to rank programs only by their entry bar. But we are more than welcome to receive information like these about the program placement, target school, etc.

I noticed that the PR is largely based on the quality of the program instead of the bar, would you like to make any modifications based on the entry bar?

**Comment by yuhengcai1** [comment]
The most important one is the bar is hard to measure and the samples can hardly to be fully obversed. 
But mostly of my update is based on the traditional understanding of the programs, like UVA/NYU, even not considering about the placement, NYU DS does not have the higher entry bar than UMICH. And UVA MSCS was not a popular University in Mainland China, but it have a great reputation and traditional is much better than BU. I think this update is reasonable. 
And for GT CSE, I find several persons are also holding UIUC MCS this year so it will be hard to measure the bar as well.
The entry bar is hard to measure as well, the diversity have a very large effectiveness in application as well. 
And there are also a lot of tiny mistakes if you look at the ranking clearfully, firstly UIUC MSCS is definitily harder to get into than Upenn DS.

**Comment by xichenpan** [comment]
@yuhengcai1 Thanks a lot for the reply! sorry for delayed response due to my arrival at nyc. We would like to stay focus on the bar ranking cause though it is somehow hard to eval the bar, but it is more practical than rank the best university. We believe for every individual, there is a best university ranking for him/her related to his/her own situation. Till now, we try to collect more than 1000+ datapoints from applicants and try to figure out the bar ranking from correlation (like one acc by some programs but rejs by others). It is true that diversity exits in admission process, but our main users are Chinese students, so it still work.

But apart from bar ranking, we would like to provide some insightful points as well. Like the info about UVA is really useful for applicants to make final decisions, so I will update the infomation you mentioned into the website.

btw, from my observation, it is harder for applicants from mainland China to get into DS@UPenn than MSCS@UIUC, cause for UIUC you only need good research, but for UPenn, you do not actually know what they want :(

**Comment by xichenpan** [comment]
as for UVA, we know few about the programs below B+, according to 3 records in datapoints, we find it easy to get in, so maybe we can move it to B

**Pull request closed without merging**
